export enum IconsEnum {
  Dark = "moon",
  Light = "sun",
  Book = "book",
  Heart = "heart",
  Home = "home",
  Arrow = "arrow",
  Calendar = "calendar",
  Search = "search",
  Menu = "menu",
  Cross = "cross",
  Location = "location",
  FavHeart = "fav-heart",
  Check = "checkmark",
  EYE = "eye",
  CLOSE_EYE = "eye-off",
}
