import './scripts/common/current';
import './scripts/common/mobileMenu';
import './scripts/common/authMenu';
import './scripts/firebase/authState';
import './scripts/firebase/logIn';
import './scripts/firebase/logOut';
import './scripts/favorite/favoriteBlock';
import './scripts/common/newsCardFromStorage';
import './scripts/favorite/themeFavorite';
import './scripts/favorite/themeFavoriteMobile';
// import './scripts/favorite/searchNewsfromFavoriteStorage';
